Alpha preview
MostroP2P/mobile pull request #31
Opened 2024-11-15 17:48 UTC by chebizarro

### *This is a preview only and should not be used in a production environment!*

This PR brings the repo to am Android buildable state where it can interact with a Mostro daemon and Nostr relay.

On startup, it connects to a relay running on port 7000 on either 127.0.0.1 or 10.0.2.2 if running in an emulator. The relays and the mostro daemon public key can be configured in the file `lib/core/config.dart`

Currently this preview allows for:
- Add Buy/Sell Orders
- Take Buy/Sell Orders

It still lacks a UI for finalizing orders

Only ephemeral keys are used for orders, so once again, *do not use in a production environment*

2024-11-21 16:37 UTC, Catrya requested changes
Hi @chebizarro great job! congratulations.

There are some things that can be improved when displaying orders such as:

- Orders that have ranges are not being displayed correctly, it only shows the lower value. For example: purchase order of 210-600 cup, it only shows one order for 210 cup
![diff](https://github.com/user-attachments/assets/bee5cf2b-697c-498b-85cb-60465ee04fa4)


- If the maker of the order has `"rating", "none"` the client displays the order, but if the maker was previously rated, this appears in the logs `Another exception was thrown: FormatException: Missing rating object in JSON` and the client shows a red error. Also, it does not show any order that has been published after that one 
![Captura desde 2024-11-21 11-33-26](https://github.com/user-attachments/assets/ead7ea9f-31a2-433c-bdb8-0896c9ebedd8)

2024-11-21 17:28 UTC, Catrya reviewed
I think that when someone presses an order to see its details, if they don't want to take it, and they press Cancel, there is no need to display the message that you have cancelled the order, because in reality the user didn't cancel it, they just didn't take it.

I think that automatically returning the user to the main screen would be fine, without them having to press another button to do so.

![Captura desde 2024-11-21 12-21-47](https://github.com/user-attachments/assets/39589511-f161-4c34-b062-68af7750d5ac)

2024-11-21 18:05 UTC, Catrya reviewed
In the purchase orders, it says: `offering X sats for Y fiat` but it seems incorrect to me that way, since the buyer offers the fiat, not the btc. 

I think it should swap the order in which they appear and put `offering Y fiat for X sats`, and if it is a market price order perhaps it should say `offering Y fiat for sats` without the value.

Another way to put it would be (using the fiat USD example): 
For purchase orders:
- Market price orders: `Buying Sats for X USD`
- Fixed orders:
`Buying Y sats for X USD`

For sales orders:
- Market price orders:
`Selling sats for X USD`
- Fixed orders:
`Selling Y sats for X USD`

What do you think @chebizarro ?

2024-11-21 21:00 UTC, Catrya commented
@chebizarro This might be useful for UI https://github.com/MostroP2P/mobile/discussions/26
If you want we can talk about more ideas in that UI discussion.

2024-11-22 15:39 UTC, Catrya commented
>  Currently this preview allows for:
> - Take Buy/Sell Orders

Hi @chebizarro Sorry for so many messages 😅 I can't get it to take an order. When I press Continue to take an order, the order remains in pending status. It seems that Mostro is not receiving the message from takesell or takebuy. 
Maybe I'm doing something wrong when testing it. Any suggestions on how to do this?

2024-11-26 23:01 UTC, chebizarro commented
The latest commits address:
- @grunch request to implement Code Rabbit AI suggestions
 - @Catrya bugs/suggestions with the exception of Take/Sell Orders
After this PR is merged I will be able to make much smaller PRs that will address specific issues

2024-11-27 18:59 UTC, chebizarro commented on lib/core/utils/nostr_utils.dart
> +  static Future<NostrEvent> createNIP59Event(
Support for encrypting DMs to send to the mostro daemon as per issue #3

2024-11-27 19:01 UTC, chebizarro commented on lib/core/utils/nostr_utils.dart
> +  static Future<NostrEvent> decryptNIP59Event(
Support for decrypting DMs from mostro as per issue #3

2024-11-27 19:03 UTC, chebizarro commented on lib/data/models/enums/action.dart
> +enum Action {
Introduces the Actin type for the mostro message as per issue #3

2024-11-27 19:03 UTC, chebizarro commented on lib/data/models/mostro_message.dart
> +import 'dart:convert';
Implements the mostro message kind as per #3

2024-11-27 19:06 UTC, chebizarro commented on pubspec.yaml
> +  nip44:
NIP-44 support was implemented as per issue #3 but bundled into a separate library as it has utility for other Nostr developers. This library can be transferred to the mostro project if desired

2024-11-27 19:21 UTC, chebizarro commented on lib/data/models/session.dart
> +import 'package:dart_nostr/dart_nostr.dart';
The Session object addresses issue #28

2024-11-27 22:04 UTC, Catrya approved these changes
Hi @chebizarro, thanks for considering the comments I made to you. I've already test it and it shows the pending orders very well

Take sell/buy orders can be left for another PR, no problem, great job!

2024-11-28 15:40 UTC, grunch commented
> The latest commits address:
> 
>     * @grunch request to implement Code Rabbit AI suggestions
> 
>     * @Catrya bugs/suggestions with the exception of Take/Sell Orders
>       After this PR is merged I will be able to make much smaller PRs that will address specific issues

Understood, but the description of this PR has this written:

```
Currently this preview allows for:

    Add Buy/Sell Orders
    Take Buy/Sell Orders
```

Could you please update this removing what we are not going to have on this PR so we can merge it? thanks

2024-12-13 20:10 UTC, grunch commented
Hi @chebizarro this is ready to be merged?

2024-12-13 20:17 UTC, chebizarro commented
> Hi @chebizarro this is ready to be merged?

It is, I edited the original the original PR comment to reflect the actual features included. Once this is merged, I'll open another PR with the complete take buy/sell and make buy/sell order features from the development branch.

2024-12-13 20:30 UTC, grunch commented
great! please next time ping me so we can merge right after is done

2024-12-13 20:30 UTC, grunch approved these changes
tACK 

great job @chebizarro !!!

2024-12-13 20:31 UTC, merged